version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/neurex-web"
    schedule:
      interval: "daily"
    groups:
      npm_and_yarn:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/neurex-landing"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/neurex-cli"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
