import os
import sys
import socket
import secrets
import webbrowser
from pathlib import Path
import psutil
import requests
import questionary
from rich.console import Console
from rich.panel import Panel
from rich.text import Text
from rich.progress import Progress, SpinnerColumn, TextColumn
from rich import print as rprint

console = Console()

def get_network_interfaces():
    """Detect all available network interfaces and their IPs."""
    interfaces = []
    stats = psutil.net_if_addrs()
    for name, addresses in stats.items():
        for addr in addresses:
            if addr.family == socket.AF_INET: # IPv4
                interfaces.append({
                    "name": name,
                    "ip": addr.address,
                    "display": f"{name} ({addr.address})"
                })
    return interfaces

def get_wan_ip():
    try:
        return requests.get("https://api.ipify.org", timeout=3).text
    except:
        return "Unknown"

def show_banner():
    banner = """
[bold cyan]
███╗   ██╗███████╗██╗   ██╗██████╗ ███████╗██╗  ██╗
████╗  ██║██╔════╝██║   ██║██╔══██╗██╔════╝╚██╗██╔╝
██╔██╗ ██║█████╗  ██║   ██║██████╔╝█████╗   ╚███╔╝ 
██║╚██╗██║██╔══╝  ██║   ██║██╔══██╗██╔══╝   ██╔██╗ 
██║ ╚████║███████╗╚██████╔╝██║  ██║███████╗██╔╝ ██╗
╚═╝  ╚═══╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝
[/bold cyan]
[bold white]Enterprise Agent Platform — Interactive Installer[/bold white]
    """
    console.print(Panel(banner, border_style="cyan", expand=False))

def main():
    os.system('clear' if os.name == 'posix' else 'cls')
    show_banner()
    
    # 1. Installation Paths
    console.print("\n[bold magenta]1. System Configuration[/bold magenta]")
    
    default_path = str(Path.cwd().absolute())
    install_path = questionary.path(
        "Where should Neurex be installed?",
        default=default_path
    ).ask()
    
    llm_path = questionary.path(
        "Where should LLM models be stored? (Requires significant disk space)",
        default=str(Path(install_path) / ".models")
    ).ask()

    # 2. Network Interface
    console.print("\n[bold magenta]2. Network Binding[/bold magenta]")
    interfaces = get_network_interfaces()
    choices = [f"{iface['display']}" for iface in interfaces]
    choices.append("0.0.0.0 (Bind to all interfaces - Default)")
    
    bind_choice = questionary.select(
        "Which network interface should Neurex bind to?",
        choices=choices,
        default="0.0.0.0 (Bind to all interfaces - Default)"
    ).ask()
    
    bind_ip = "0.0.0.0"
    if bind_choice != "0.0.0.0 (Bind to all interfaces - Default)":
        bind_ip = bind_choice.split("(")[1].replace(")", "")

    # 3. Domain & Proxy
    console.print("\n[bold magenta]3. Proxy & Access[/bold magenta]")
    setup_type = questionary.select(
        "How will you access Neurex?",
        choices=[
            "Internal Network Only (LAN IP / Tailscale / Localhost)",
            "External Domain (Automatic Let's Encrypt SSL via Caddy)",
            "Behind Existing Proxy (Nginx/Traefik/Cloudflare Tunnel)"
        ]
    ).ask()

    domain = ""
    use_https = False
    
    if "External Domain" in setup_type:
        domain = questionary.text("Enter your Fully Qualified Domain Name (e.g., neurex.yourdomain.com):").ask()
        use_https = True
    elif "Internal" in setup_type:
        use_https = questionary.confirm("Enable mTLS / Self-Signed HTTPS for Internal Network?").ask()
        domain = bind_ip if bind_ip != "0.0.0.0" else "localhost"
    else:
        domain = "localhost" # Behind another proxy

    # 4. Generate Secrets
    console.print("\n[bold magenta]4. Generating Security Perimeters[/bold magenta]")
    
    with Progress(SpinnerColumn(), TextColumn("[progress.description]{task.description}"), transient=True) as progress:
        task1 = progress.add_task("Generating One-Time Admin Password...", total=100)
        otp = secrets.token_urlsafe(16)
        progress.update(task1, advance=50)
        
        jwt_secret = secrets.token_hex(32)
        progress.update(task1, advance=50)

    # 5. Write Configuration
    env_content = f"""# Automatically generated by Neurex Installer
WORKSPACE_PATH={install_path}/workspace
LLM_MODELS_PATH={llm_path}
BIND_IP={bind_ip}
NEUREX_DOMAIN={domain}
ADMIN_OTP={otp}
JWT_SECRET={jwt_secret}
USE_HTTPS={str(use_https).lower()}
AUTONOMY_LEVEL=limited
ENABLE_AGENT_INTERNET=false
"""
    
    Path(".env").write_text(env_content)
    console.print("[green]✔[/green] .env generated successfully.")

    # 6. Gather Info
    lan_ip = "127.0.0.1" if bind_ip == "0.0.0.0" else bind_ip
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(("8.8.8.8", 80))
        lan_ip = s.getsockname()[0]
        s.close()
    except:
        pass
        
    wan_ip = get_wan_ip()
    
    protocol = "https" if use_https else "http"
    access_url = f"{protocol}://{domain if domain != 'localhost' else lan_ip}:8080"

    # 7. Final Summary Panel
    summary = f"""
[bold green]Installation Configuration Complete![/bold green]

[bold yellow]Network Topology:[/bold yellow]
• [cyan]LAN IP:[/cyan]    {lan_ip}
• [cyan]WAN IP:[/cyan]    {wan_ip}
• [cyan]FQDN:[/cyan]      {domain if domain else 'None'}
• [cyan]Binding:[/cyan]   {bind_ip}:8080

[bold yellow]Storage:[/bold yellow]
• [cyan]App Root:[/cyan]  {install_path}
• [cyan]Models:[/cyan]    {llm_path}

[bold red]Security Notice — DO NOT LOSE THIS:[/bold red]
Your Initial Admin Onboarding Password is:
[bold white on red] {otp} [/bold white on red]

[dim]Next Steps:[/dim]
1. Run [bold]docker-compose up -d[/bold] to start the services.
2. Navigate to [blue underline]{access_url}/onboarding[/blue underline]
"""
    console.print(Panel(summary, title="[bold]Neurex Deployment Summary[/bold]", border_style="green"))

    # 8. Open Browser
    if questionary.confirm("Launch browser to onboarding page now?").ask():
        webbrowser.open(f"{access_url}/onboarding?token={otp}")
        console.print("[dim]Browser launched.[/dim]")
    
    console.print("\n[bold cyan]Welcome to the Future of Development.[/bold cyan] 🚀\n")

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        console.print("\n[red]Installation aborted by user.[/red]")
        sys.exit(1)
