[pytest]
norecursedirs = scripts scratch .venv sandbox
testpaths = tests
python_files = test_*.py
pythonpath = . ..
filterwarnings =
    ignore::DeprecationWarning
    ignore::sqlalchemy.exc.SAWarning
    ignore::pytest.PytestUnhandledThreadExceptionWarning


