line-length = 100
target-version = "py312"
exclude = ["**/_quarantine/**"]

[lint]
select = ["E", "F", "I", "N", "UP", "ASYNC"]
ignore = ["E501", "E402", "N806", "ASYNC220", "ASYNC221", "ASYNC240", "ASYNC230", "ASYNC110", "UP042", "E701", "F841"]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
